[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  10
    Rotate_Wait       30
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On

[FILTER]
    Name    modify
    Match   docker.*
    Add     application boresakshi

[OUTPUT]
    Name        loki
    Match       docker.*
    Host        loki
    Port        3100
    Labels      job=boresakshi,application=$application
    Line_Format json
    Retry_Limit False
